films_index:
    path:     /
    defaults: { _controller: "FilmoBundle:Films:index" }
    methods:  GET

films_show:
    path:     /{id}/show
    defaults: { _controller: "FilmoBundle:Films:show" }
    methods:  GET

films_new:
    path:     /new
    defaults: { _controller: "FilmoBundle:Films:new" }
    methods:  [GET, POST]

films_edit:
    path:     /{id}/edit
    defaults: { _controller: "FilmoBundle:Films:edit" }
    methods:  [GET, POST]

films_delete:
    path:     /{id}/delete
    defaults: { _controller: "FilmoBundle:Films:delete" }
    methods:  DELETE
