filmo_homepage:
    path:     /
    defaults: { _controller: FilmoBundle:Default:accueil }
categorie_ajout:
    path:     /categorie/ajout
    defaults: { _controller: FilmoBundle:Categorie:ajout }
categorie_affiche:
    path:     /categorie
    defaults: { _controller: FilmoBundle:Categorie:show }
acteur_ajout:
    path:     /acteur/ajout
    defaults: { _controller: FilmoBundle:Acteur:ajout }
acteur_affiche:
    path:     /acteur
    defaults: { _controller: FilmoBundle:Acteur:show }
acteur_edit:
    path:     /acteur/edit/{id}
    defaults: { _controller: FilmoBundle:Acteur:edit }
acteur_del:
    path:     /acteur/del/{id}
    defaults: { _controller: FilmoBundle:Acteur:del }