filmo_homepage:
    path:     /otherrr
    defaults: { _controller: FilmoBundle:Default:index }
categorie_ajout:
    path:     /categorie/ajout
    defaults: { _controller: FilmoBundle:Categorie:ajout }
categorie_affiche:
    path:     /categorie
    defaults: { _controller: FilmoBundle:Categorie:show }
acteur_ajout:
    path:     /acteur/ajout
    defaults: { _controller: FilmoBundle:Acteur:ajout }
acteur_affiche:
    path:     /acteur
    defaults: { _controller: FilmoBundle:Acteur:show }